# Introduction {.unnumbered}

## What is bioinformatics anyway?

Bioinformatics is a scientific discipline that develops and utilises computational methods to analyse large amounts of biological data, typically molecular sequence data such as DNA, RNA and amino acid sequences, as well as annotations describing those sequences. It spans the entire spectrum of collecting, storing and annotating data, to modelling, predicting and discovering new biological insights, from the level of individual molecules, to cells, organisms and populations. Bioinformatics is a highly interdisciplinary field that brings together many different types of researchers, including biologists, computer scientists, statisticians, clinicians and even chemists and physicists. A closely related term that you might see being used interchangeably with bioinformatics, is _computational biology_. However, there is no consensus on a clear distinction between the two[^1]; like so many things in nature (e.g. the concept of a species), scientific disciplines are often hard to define and delineate.

A few examples of popular topics in bioinformatics are:

-	Population genetics and molecular epidemiology (what we will be focusing on in this course)
-	Analysis of gene/protein expression and regulation, e.g. in disease models (for RNA-seq spatial and single-cell approaches are become more prevalent)
-	Structural bioinformatics, e.g. predicting the structure of proteins
-	Network and systems biology: mapping and analysing the relationships between interacting biomolecules such as proteins, metabolites and their signal cascades, e.g. gene regulatory networks)
-	Comparative genomics and phylogenetics: studying the ancestry of species, genes or entire genomes through time and space
-	Genomic annotation and cataloguing genetic mutations and associated diseases in databases

[^1]:
  - [https://biology.stackexchange.com/questions/3192/is-computational-biology-different-from-bioinformatics](https://biology.stackexchange.com/questions/3192/is-computational-biology-different-from-bioinformatics)
  - [https://www.nature.com/subjects/computational-biology-and-bioinformatics](https://www.nature.com/subjects/computational-biology-and-bioinformatics)
  - [https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-bioinformatics/](https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-bioinformatics/)
  - [https://www.genome.gov/genetics-glossary/Bioinformatics](https://www.genome.gov/genetics-glossary/Bioinformatics)

## Computational thinking

We hope that this course can teach you a few computational thinking and problem solving skills that will help you along your bioinformatics journey. The learning curve in computational biology can be quite steep at times and the path is littered with arcane commands and obtuse syntax, but as you practice the concepts introduced in this course on your own, your command-line efficiency will improve and you will start to spot similarities across different types of environments and languages. Through this course, we hope to arm you with the necessary skills to make tasks like running custom analysis scripts or installing bioinformatics software seem a little less daunting.
